services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: golang_crud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: >
      bash -c "
        apt-get update && 
        apt-get install -y postgresql-15-pgvector && 
        docker-entrypoint.sh postgres
      "
    networks:
      - app_network
      
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - app_network

  ollama-setup:
    image: ollama/ollama
    depends_on:
      - ollama
    volumes:
      - ollama_data:/root/.ollama
    command: >
      sh -c "
        sleep 20 &&
        echo 'Pulling nomic-embed-text model...' &&
        ollama pull nomic-embed-text &&
        echo 'Model downloaded successfully!'
      "
    restart: "no"
    networks:
      - app_network

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - ollama
    environment:
      - DATABASE_URL=postgres://postgres:password123@postgres:5432/golang_crud?sslmode=disable
      - OLLAMA_URL=http://ollama:11434
    networks:
      - app_network
    restart: unless-stopped

volumes:
  postgres_data:
  ollama_data:

networks:
  app_network:
    driver: bridge
